# Generated by Django 4.2.2 on 2023-09-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=8.45),
            preserve_default=False,
        ),
    ]
